### ISSUE TITLE
Chrome extension succeeds inconsistently

### ISSUE THREAD

**Issue by maxfierke** [IonicaBizau/github-old-header#2]
I was able to get it work for a couple page loads, but for others, the extension does not seem to be successfully injecting itself into `<head>`.

Using the Chrome extension from the web store.

Other enabled extensions:
- AngularJS Batarang

**Comment by IonicaBizau** [comment]
Can you reproduce it every time? How can I reproduce the issue?
I'm also using the extension from web store.

Thanks! :four_leaf_clover:

**Comment by maxfierke** [comment]
Honestly, I just keep hard refreshing (`Ctrl+Shift+R`) until it works. Sometimes the header changes, sometimes it doesn't.  There doesn't seem to be a prescription for when it does and doesn't work, based on user behavior.

I haven't drilled into it, but perhaps a subtle DOM change or GitHub's use of PJAX would be causing it?

**Comment by IonicaBizau** [comment]
@maxfierke Hmm, I don't think PJAX causes it. I still cannot reproduce, but maybe listening to [`DOMContentLoaded`](https://github.com/IonicaBizau/github-old-header/blob/master/extension/tmpl.js#L1) instead of `load` would be better.

What I notice is only a small delay until the script is loaded, but that's supposed to be so.

**Comment by IonicaBizau** [comment]
Maybe you can try the Tampermonkey way, edit the script to use `DOMContentLoaded` and see if there is a change.

**Comment by IonicaBizau** [comment]
https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded -- interesting stuff:

> A very different event - load - should be used only to detect a fully-loaded page. It is an incredibly popular mistake for people to use load where DOMContentLoaded would be much more appropriate, so be cautious.

Didn't know that. :books:

**Comment by IonicaBizau** [comment]
@maxfierke Could you please provide the browser version and OS you are running?

**Comment by maxfierke** [comment]
Chrome 44 (beta?) on Windows 7 (work machine :p)

**Comment by IonicaBizau** [comment]
@maxfierke :ship: `2.1.2` Hope this got fixed.

**Comment by maxfierke** [comment]
Yup. Seems to work consistently now. Thanks!

**Comment by IonicaBizau** [comment]
@maxfierke Oh, awesome! :tada: I guess the update delay is less now. Maybe, is it possible to update the HTML _before_ rendering the page?
