### ISSUE TITLE
Broke

### ISSUE THREAD

**Issue by WebFreak001** [IonicaBizau/github-old-header#8]
not sure if its a chrome update or github's fault but the extension doesn't do anything anymore

**Comment by IonicaBizau** [comment]
@WebFreak001 Thanks for bringing this in attention. I noticed it and fixed it locally but forgot to update the extension. :grin: Taking care of it **right now**! :crystal_ball:

**Comment by IonicaBizau** [comment]
:ship: **`2.4.0`** :tada:
